// Variable point_interet avec les informations définies dans QGIS ainsi que leur position en coordonnées. 

var point_interet = {
    "type": "FeatureCollection",
    "name": "point_interet",
    "crs": { "type": "name", "properties": { "name": "urn:ogc:def:crs:OGC:1.3:CRS84" } },
    "features": [
    { "type": "Feature", "properties": { "id": "generomont", "nom": "Monte Generoso", "type": "sommet" }, "geometry": { "type": "Point", "coordinates": [ 9.0199, 45.93128 ] } },
    { "type": "Feature", "properties": { "id": "refugePrab", "nom": "Refuge Prabello", "type": "refuge" }, "geometry": { "type": "Point", "coordinates": [ 9.07284, 45.91323 ] } },
    { "type": "Feature", "properties": { "id": "parkgener", "nom": "Parking Bellavista", "type": "parking" }, "geometry": { "type": "Point", "coordinates": [ 9.0008, 45.90662 ] } },
    { "type": "Feature", "properties": { "id": "restoPeon", "nom": "Osteria La Peonia", "type": "restaurant" }, "geometry": { "type": "Point", "coordinates": [ 9.00257, 45.90733 ] } },
    { "type": "Feature", "properties": { "id": "parkCabbio", "nom": "Parking à Cabbio", "type": "parking" }, "geometry": { "type": "Point", "coordinates": [ 9.04665, 45.89879 ] } },
    { "type": "Feature", "properties": { "id": "parkeau", "nom": "Parking à Monteggio", "type": "parking" }, "geometry": { "type": "Point", "coordinates": [ 8.82206, 45.99175 ] } },
    { "type": "Feature", "properties": { "id": "parkbar", "nom": "Parking à Bidogno", "type": "parking" }, "geometry": { "type": "Point", "coordinates": [ 9.00026, 46.07905 ] } },
    { "type": "Feature", "properties": { "id": "refugebar", "nom": "Refuge Monte Bar", "type": "refuge" }, "geometry": { "type": "Point", "coordinates": [ 9.01401, 46.09995 ] } },
    { "type": "Feature", "properties": { "id": "parkbar", "nom": "Parking à l'Alpage de Rompiago", "type": "parking" }, "geometry": { "type": "Point", "coordinates": [ 8.99964, 46.09152 ] } },
    { "type": "Feature", "properties": { "id": "parktibet", "nom": "Parking à Monte Carasso", "type": "parking" }, "geometry": { "type": "Point", "coordinates": [ 8.99589, 46.18866 ] } },
    { "type": "Feature", "properties": { "id": "parktibet", "nom": "Parking à Monte Carasso", "type": "parking" }, "geometry": { "type": "Point", "coordinates": [ 8.99713, 46.18919 ] } },
    { "type": "Feature", "properties": { "id": "parktibet", "nom": "Parking à Monte Carasso", "type": "parking" }, "geometry": { "type": "Point", "coordinates": [ 8.99713, 46.18671 ] } },
    { "type": "Feature", "properties": { "id": "parktibet", "nom": "Parking à Monte Carasso", "type": "parking" }, "geometry": { "type": "Point", "coordinates": [ 8.99645, 46.18892 ] } },
    { "type": "Feature", "properties": { "id": "parktibet", "nom": "Parking à Monte Carasso", "type": "parking" }, "geometry": { "type": "Point", "coordinates": [ 8.99681, 46.18915 ] } },
    { "type": "Feature", "properties": { "id": "parktibet", "nom": "Parking à Monte Carasso", "type": "parking" }, "geometry": { "type": "Point", "coordinates": [ 8.99633, 46.18796 ] } },
    { "type": "Feature", "properties": { "id": "parktibet", "nom": "Parking à Monte Carasso", "type": "parking" }, "geometry": { "type": "Point", "coordinates": [ 8.99158, 46.18703 ] } },
    { "type": "Feature", "properties": { "id": "parktibet", "nom": "Parking à Monte Carasso", "type": "parking" }, "geometry": { "type": "Point", "coordinates": [ 8.99195, 46.18666 ] } },
    { "type": "Feature", "properties": { "id": "parktibet", "nom": "Parking à Monte Carasso", "type": "parking" }, "geometry": { "type": "Point", "coordinates": [ 8.99217, 46.18663 ] } },
    { "type": "Feature", "properties": { "id": "resttibet", "nom": "Osteria Curzutt", "type": "restaurant" }, "geometry": { "type": "Point", "coordinates": [ 8.99306, 46.19459 ] } },
    { "type": "Feature", "properties": { "id": "parklodano", "nom": "Parking à Lodano", "type": "parking" }, "geometry": { "type": "Point", "coordinates": [ 8.68547, 46.25845 ] } },
    { "type": "Feature", "properties": { "id": "parklodano", "nom": "Parking à Lodano", "type": "parking" }, "geometry": { "type": "Point", "coordinates": [ 8.68517, 46.25844 ] } },
    { "type": "Feature", "properties": { "id": "restocaras", "nom": "Osteria Cramalina", "type": "restaurant" }, "geometry": { "type": "Point", "coordinates": [ 8.68474, 46.2573 ] } },
    { "type": "Feature", "properties": { "id": "garebella", "nom": "Gare intermédiaire Bellavista", "type": "gare" }, "geometry": { "type": "Point", "coordinates": [ 9.00137, 45.91125 ] } },
    { "type": "Feature", "properties": { "id": "garecapol", "nom": "Gare de Capolago", "type": "gare" }, "geometry": { "type": "Point", "coordinates": [ 8.97888, 45.90288 ] } },
    { "type": "Feature", "properties": { "id": "parkgenero", "nom": "Parking Monte Genenroso", "type": "parking" }, "geometry": { "type": "Point", "coordinates": [ 8.97719, 45.90166 ] } },
    { "type": "Feature", "properties": { "id": "arretcabbi", "nom": "Arrêt \"Cabbio, Posta\"", "type": "arret" }, "geometry": { "type": "Point", "coordinates": [ 9.04527, 45.89824 ] } },
    { "type": "Feature", "properties": { "id": "arretbidog", "nom": "Arrêt \"Bidogno, Paese\"", "type": "arret" }, "geometry": { "type": "Point", "coordinates": [ 8.99814, 46.07799 ] } },
    { "type": "Feature", "properties": { "id": "parkbar", "nom": "Parking intermédiaire réfuge Monte Bar", "type": "parking" }, "geometry": { "type": "Point", "coordinates": [ 8.99687, 46.08468 ] } },
    { "type": "Feature", "properties": { "id": "teleptibet", "nom": "Téléphérique Monte Carasso - Mornera", "type": "téléphérique" }, "geometry": { "type": "Point", "coordinates": [ 8.99754, 46.18933 ] } },
    { "type": "Feature", "properties": { "id": "teleptibet", "nom": "Arrêt intermédiaire Curzutt", "type": "téléphérique" }, "geometry": { "type": "Point", "coordinates": [ 8.99305, 46.19396 ] } },
    { "type": "Feature", "properties": { "id": "teleptibet", "nom": "Téléphérique Monte Carasso - Mornera", "type": "téléphérique" }, "geometry": { "type": "Point", "coordinates": [ 8.97946, 46.20795 ] } },
    { "type": "Feature", "properties": { "id": "teleptibet", "nom": "Arrêt intermédiaire Pientina", "type": "téléphérique" }, "geometry": { "type": "Point", "coordinates": [ 8.98592, 46.20128 ] } },
    { "type": "Feature", "properties": { "id": "arretcaras", "nom": "Arrêt \"Monte Carasso, Cunvént\"", "type": "arret" }, "geometry": { "type": "Point", "coordinates": [ 8.99663, 46.18826 ] } },
    { "type": "Feature", "properties": { "id": "arretcaras", "nom": "Arrêt \"Sementina, Via Locarno\"", "type": "arret" }, "geometry": { "type": "Point", "coordinates": [ 8.99127, 46.18567 ] } },
    { "type": "Feature", "properties": { "id": "restogener", "nom": "Fiore di Pietra", "type": "restaurant" }, "geometry": { "type": "Point", "coordinates": [ 9.0187, 45.9281 ] } },
    { "type": "Feature", "properties": { "id": "ponttibet", "nom": "Pont Tibétan \"Carasc\"", "type": "pont" }, "geometry": { "type": "Point", "coordinates": [ 8.97464, 46.19491 ] } },
    { "type": "Feature", "properties": { "id": "parktamaro", "nom": "Parking Monte Tamaro", "type": "parking" }, "geometry": { "type": "Point", "coordinates": [ 8.91991, 46.12631 ] } },
    { "type": "Feature", "properties": { "id": "teleptamaro", "nom": "Téléphérique Monte Tamaro", "type": "téléphérique" }, "geometry": { "type": "Point", "coordinates": [ 8.91965, 46.12703 ] } },
    { "type": "Feature", "properties": { "id": "teleptamaro", "nom": "Téléphérique Monte Tamaro", "type": "téléphérique" }, "geometry": { "type": "Point", "coordinates": [ 8.89352, 46.11681 ] } },
    { "type": "Feature", "properties": { "id": "alpefoppa", "nom": "Alpe Foppa", "type": "restaurant" }, "geometry": { "type": "Point", "coordinates": [ 8.89308, 46.11734 ] } },
    { "type": "Feature", "properties": { "id": "refugetamaro", "nom": "Refuge Monte Tamaro", "type": "refuge" }, "geometry": { "type": "Point", "coordinates": [ 8.88109, 46.10824 ] } },
    { "type": "Feature", "properties": { "id": "sommettamaro", "nom": "Monte Tamaro", "type": "sommet" }, "geometry": { "type": "Point", "coordinates": [ 8.86604, 46.10389 ] } },
    { "type": "Feature", "properties": { "id": "sommetgradic", "nom": "Monte Gradiccioli", "type": "sommet" }, "geometry": { "type": "Point", "coordinates": [ 8.86586, 46.08419 ] } },
    { "type": "Feature", "properties": { "id": "sommetpola", "nom": "Monte Pola", "type": "sommet" }, "geometry": { "type": "Point", "coordinates": [ 8.85589, 46.07531 ] } },
    { "type": "Feature", "properties": { "id": "sommetmagno", "nom": "Monte Magno", "type": "sommet" }, "geometry": { "type": "Point", "coordinates": [ 8.86065, 46.06419 ] } },
    { "type": "Feature", "properties": { "id": "sommetzotton", "nom": "Zottone", "type": "sommet" }, "geometry": { "type": "Point", "coordinates": [ 8.85503, 46.05443 ] } },
    { "type": "Feature", "properties": { "id": "sommetbreno", "nom": "Poncione di Breno", "type": "sommet" }, "geometry": { "type": "Point", "coordinates": [ 8.84753, 46.04845 ] } },
    { "type": "Feature", "properties": { "id": "sommetlema", "nom": "Monte Lema", "type": "sommet" }, "geometry": { "type": "Point", "coordinates": [ 8.83284, 46.04052 ] } },
    { "type": "Feature", "properties": { "id": "teleplema", "nom": "Téléphérique Monte Lema", "type": "téléphérique" }, "geometry": { "type": "Point", "coordinates": [ 8.8348, 46.04072 ] } },
    { "type": "Feature", "properties": { "id": "teleplema", "nom": "Téléphérique Monte Lema", "type": "téléphérique" }, "geometry": { "type": "Point", "coordinates": [ 8.85626, 46.02372 ] } },
    { "type": "Feature", "properties": { "id": "parkinglema", "nom": "Parking Monte Lema", "type": "parking" }, "geometry": { "type": "Point", "coordinates": [ 8.85592, 46.02382 ] } },
    { "type": "Feature", "properties": { "id": "parkinglema", "nom": "Parking Monte Lema", "type": "parking" }, "geometry": { "type": "Point", "coordinates": [ 8.85645, 46.02392 ] } },
    { "type": "Feature", "properties": { "id": "arretmiglie", "nom": "Arrêt \"Miglieglia, Paese\"", "type": "arret" }, "geometry": { "type": "Point", "coordinates": [ 8.85734, 46.02383 ] } },
    { "type": "Feature", "properties": { "id": "garetamaro", "nom": "Gare Riviera-Bironico", "type": "gare" }, "geometry": { "type": "Point", "coordinates": [ 8.92498, 46.12409 ] } },
    { "type": "Feature", "properties": { "id": "arretgandria", "nom": "Arrêt \"Gandria, Strada\"", "type": "arret" }, "geometry": { "type": "Point", "coordinates": [ 9.00218, 46.00604 ] } },
    { "type": "Feature", "properties": { "id": "parkcastagno", "nom": "Parking à Castagnola", "type": "parking" }, "geometry": { "type": "Point", "coordinates": [ 8.97631, 46.00134 ] } },
    { "type": "Feature", "properties": { "id": "parkcastagno", "nom": "Parking à Castagnola", "type": "parking" }, "geometry": { "type": "Point", "coordinates": [ 8.97693, 46.00121 ] } },
    { "type": "Feature", "properties": { "id": "arretcastagn", "nom": "Arrêt \"Castagnola, Posta\"", "type": "arret" }, "geometry": { "type": "Point", "coordinates": [ 8.97647, 46.00136 ] } },
    { "type": "Feature", "properties": { "id": "parkmeride", "nom": "Parking à Meride", "type": "parking" }, "geometry": { "type": "Point", "coordinates": [ 8.95059, 45.89017 ] } },
    { "type": "Feature", "properties": { "id": "parkmeride", "nom": "Parking à Meride", "type": "parking" }, "geometry": { "type": "Point", "coordinates": [ 8.95122, 45.89063 ] } },
    { "type": "Feature", "properties": { "id": "arretmeride", "nom": "Arrêt \"Meride, Paese\"", "type": "arret" }, "geometry": { "type": "Point", "coordinates": [ 8.95147, 45.89057 ] } },
    { "type": "Feature", "properties": { "id": "refugesangio", "nom": "Refuge non surveillé", "type": "refuge" }, "geometry": { "type": "Point", "coordinates": [ 8.94977, 45.91388 ] } },
    { "type": "Feature", "properties": { "id": "museesangior", "nom": "Musée des fossiles de Meride", "type": "musee" }, "geometry": { "type": "Point", "coordinates": [ 8.9529, 45.89054 ] } },
    { "type": "Feature", "properties": { "id": "refugepairol", "nom": "Refuge Pairolo", "type": "refuge" }, "geometry": { "type": "Point", "coordinates": [ 9.04487, 46.06275 ] } },
    { "type": "Feature", "properties": { "id": "arretcimader", "nom": "Arrêt \"Cimadera, Paese\"", "type": "arret" }, "geometry": { "type": "Point", "coordinates": [ 9.04551, 46.07887 ] } },
    { "type": "Feature", "properties": { "id": "parkcimadera", "nom": "Parking à Cimadera", "type": "parking" }, "geometry": { "type": "Point", "coordinates": [ 9.04676, 46.07898 ] } },
    { "type": "Feature", "properties": { "id": "parkarbedo", "nom": "Parking à Arbedo", "type": "parking" }, "geometry": { "type": "Point", "coordinates": [ 9.04766, 46.21281 ] } },
    { "type": "Feature", "properties": { "id": "parkarbedo", "nom": "Parking à Arbedo", "type": "parking" }, "geometry": { "type": "Point", "coordinates": [ 9.04785, 46.21295 ] } },
    { "type": "Feature", "properties": { "id": "arretarbedo", "nom": "Arrêt \"Arbedo, Casa Comunale\"", "type": "arret" }, "geometry": { "type": "Point", "coordinates": [ 9.04443, 46.213 ] } },
    { "type": "Feature", "properties": { "id": "arretlocarno", "nom": "Arrêt \"Monti della Trinità\"", "type": "arret" }, "geometry": { "type": "Point", "coordinates": [ 8.78986, 46.17382 ] } },
    { "type": "Feature", "properties": { "id": "parklocarno", "nom": "Parking à Locarno Monti", "type": "parking" }, "geometry": { "type": "Point", "coordinates": [ 8.78854, 46.17326 ] } },
    { "type": "Feature", "properties": { "id": "arretbrione", "nom": "Arrêt \"Minusio, Moranda\"", "type": "arret" }, "geometry": { "type": "Point", "coordinates": [ 8.80618, 46.18197 ] } },
    { "type": "Feature", "properties": { "id": "teleplocarno", "nom": "Téléphérique Cardada", "type": "téléphérique" }, "geometry": { "type": "Point", "coordinates": [ 8.78187, 46.1907 ] } },
    { "type": "Feature", "properties": { "id": "telepcardada", "nom": "Téléphérique Orselina - Cardada", "type": "téléphérique" }, "geometry": { "type": "Point", "coordinates": [ 8.79201, 46.17586 ] } },
    { "type": "Feature", "properties": { "id": "telepcardada", "nom": "Téléphérique Cardada - Cimetta", "type": "téléphérique" }, "geometry": { "type": "Point", "coordinates": [ 8.78457, 46.19361 ] } },
    { "type": "Feature", "properties": { "id": "telepcimetta", "nom": "Téléphérique Cimetta", "type": "téléphérique" }, "geometry": { "type": "Point", "coordinates": [ 8.78928, 46.20082 ] } },
    { "type": "Feature", "properties": { "id": "sommetcardad", "nom": "Sommet Cardada - Cimetta", "type": "sommet" }, "geometry": { "type": "Point", "coordinates": [ 8.79105, 46.20082 ] } },
    { "type": "Feature", "properties": { "id": "parkgiornico", "nom": "Parking à Giornico", "type": "parking" }, "geometry": { "type": "Point", "coordinates": [ 8.87052, 46.40211 ] } },
    { "type": "Feature", "properties": { "id": "arretgiornic", "nom": "Arrêt \"Giornico, Paese\"", "type": "arret" }, "geometry": { "type": "Point", "coordinates": [ 8.87724, 46.40196 ] } },
    { "type": "Feature", "properties": { "id": "arretlaverte", "nom": "Arrêt \"Lavertezzo, Paese\"", "type": "arret" }, "geometry": { "type": "Point", "coordinates": [ 8.83849, 46.2589 ] } },
    { "type": "Feature", "properties": { "id": "parklavertez", "nom": "Parking à Lavertezzo", "type": "parking" }, "geometry": { "type": "Point", "coordinates": [ 8.83766, 46.25954 ] } },
    { "type": "Feature", "properties": { "id": "parklavertez", "nom": "Parking à Lavertezzo", "type": "parking" }, "geometry": { "type": "Point", "coordinates": [ 8.83576, 46.26032 ] } },
    { "type": "Feature", "properties": { "id": "restolaverte", "nom": "Grotto al Ponte", "type": "restaurant" }, "geometry": { "type": "Point", "coordinates": [ 8.83546, 46.25983 ] } },
    { "type": "Feature", "properties": { "id": "refugesanluc", "nom": "Cabane San Lucio (CH)", "type": "refuge" }, "geometry": { "type": "Point", "coordinates": [ 9.08908, 46.08643 ] } },
    { "type": "Feature", "properties": { "id": "refugesanluc", "nom": "Refuge San Lucio (IT)", "type": "refuge" }, "geometry": { "type": "Point", "coordinates": [ 9.08976, 46.08707 ] } },
    { "type": "Feature", "properties": { "id": "arretbogno", "nom": "Arrêt \"Bogno, Paese\"", "type": "arret" }, "geometry": { "type": "Point", "coordinates": [ 9.06235, 46.08969 ] } },
    { "type": "Feature", "properties": { "id": "parkbogno", "nom": "Parking à Bogno", "type": "parking" }, "geometry": { "type": "Point", "coordinates": [ 9.06286, 46.09074 ] } },
    { "type": "Feature", "properties": { "id": "restomotta", "nom": "Osteria Motta", "type": "restaurant" }, "geometry": { "type": "Point", "coordinates": [ 8.81016, 46.27441 ] } },
    { "type": "Feature", "properties": { "id": "restolaverte", "nom": "Ristorante - Pizzeria Ai Piée", "type": "restaurant" }, "geometry": { "type": "Point", "coordinates": [ 8.79481, 46.29101 ] } },
    { "type": "Feature", "properties": { "id": "garegeneroso", "nom": "Gare Monte Generoso", "type": "gare" }, "geometry": { "type": "Point", "coordinates": [ 9.01892, 45.92789 ] } },
    { "type": "Feature", "properties": { "id": "sommetgiorgi", "nom": "Monte San Giorgio", "type": "sommet" }, "geometry": { "type": "Point", "coordinates": [ 8.9499, 45.91376 ] } },
    { "type": "Feature", "properties": { "id": "sommetgordon", "nom": "Sasso Gordona", "type": "sommet" }, "geometry": { "type": "Point", "coordinates": [ 9.08101, 45.91195 ] } },
    { "type": "Feature", "properties": { "id": "sommetbar", "nom": "Monte Bar", "type": "sommet" }, "geometry": { "type": "Point", "coordinates": [ 9.01172, 46.10765 ] } }
    ]
    };
    